name: pixel-crafter # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Pixel Art Studio
summary: Create pixel-perfect artwork with ease.
description: Dive into pixel art creation with layers, palettes, and intuitive tools for artists and game designers. Export in multiple formats and share your masterpieces.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pixel-crafter:
    command: bin/pixel-crafter-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  pixel-crafter:
    plugin: dump
    source: .
    organize:
      pixel-crafter-bin: bin/
